### PR TITLE
fix(registry): retry pull/push/tag 3 times - should help with slow networks and slow registries

### LINKED ISSUE #977: Error: net/http: transport closed before response was received
```
INFO [test-160290737]: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received
ERROR:root:Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received
Traceback (most recent call last):
  File "/app/api/models/release.py", line 88, in new
    release.publish()
  File "/app/api/models/release.py", line 135, in publish
    publish_release(source_image, self.image, deis_registry, self.get_registry_auth())
  File "/app/registry/dockerclient.py", line 196, in publish_release
    return DockerClient().publish_release(source, target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 117, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/app/registry/dockerclient.py", line 133, in push
    log_output(stream, 'push', repo, tag)
  File "/app/registry/dockerclient.py", line 175, in log_output
    stream_error(chunk, operation, repo, tag)
  File "/app/registry/dockerclient.py", line 192, in stream_error
    raise RegistryException(message)
registry.dockerclient.RegistryException: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 62, in create
    source_version=self.version
  File "/app/api/models/release.py", line 95, in new
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 181, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 258, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received
10.24.8.6 "POST /v2/apps/test-160290737/builds/ HTTP/1.1" 400 127 "Deis Client vv2.3.0-55247cf"
```

### PR DESCRIPTION
**Pull request by helgi**
Fixes #977

### CODE REVIEW

**Comment by slack** [comment]
SGTM, does this get logged anywhere that an operator would see?

**Comment by helgi** [comment]
No, I opted not to do that, tho if it fails 3 times then it will raise the errors all the way up

**Comment by felixbuenemann** [comment]
@helgi Do you think your fix will also help with errors like this:

```
Successfully built a6b761447898
Pushing to registry
remote: etail":{"message":"Put http://localhost:5555/v1/repositories/cms/: EOF"},"error":"Put http://localhost:5555/v1/repositories/cms/: EOF"}
```

I'm using an S3-backed on-cluster registry where the bucket is in the same region as the nodes.

**Comment by helgi** [comment]
It could potentially help, only if the network starts behaving or resuming works, if part of the data got pushed.

Are you seeing that consistently or sporadically?

**Comment by felixbuenemann** [comment]
Sporadically, I forgot to check all the logs to get a better insight into what went wrong.

**Pull request merged**
