### PR TITLE
docs(CONTRIBUTING): update contributing doc

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by helgi** [comment]
The deis.com doc is missing the DCO (do we care about that anymore?) and linking to troubleshooting, among other things.

**Comment by Joshua-Anderson** [comment]
The DCO is in a filed called `DCO` in the project root.

Should we link to troubleshooting in contributing docs?
Is there somewhere else you would rather link?

**Comment by helgi** [comment]
The contributing guide was caking out the DCO and semi explained it - otherwise I would have never known what it was

**Comment by helgi** [comment]
Probably enough to link to the troubleshooting docs - gets it into more hands

**Comment by Joshua-Anderson** [comment]
@helgi Would you like me to add back:

> By contributing to any Deis project you agree to its [Developer Certificate of Origin (DCO)][dco]. This document was created by the Linux Kernel community and is a simple statement that you, as a contributor, have the legal right to make the contribution.

to the document?

**Comment by helgi** [comment]
Figured that could be added to the website

**Comment by Joshua-Anderson** [comment]
Ok, I'll make a PR to the docs adding mentioning the `DCO` and adding a link to troubleshooting to the page.

**Pull request merged**
