### PR TITLE
feat(charts): Add helm charts for controller

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by helgi** [comment]
for my own curiosity - do the templates need to be in a folder called `charts` to be packaged up correctly?

**Comment by kmala** [comment]
no...i just kept them in the charts folder just to signify that the folder contains charts and nothing related to code.

**Comment by kmala** [comment]
Also it will be useful for all the repos to have charts in a common folder so that we can write script to ignore e2e if the changes are just related to chart.

**Comment by helgi** [comment]
Yeah, that's fair - Was more curious why that wasn't directly in `charts` instead of `charts/controller` but I hear ya. Sounds good to me.

**Comment by kmala** [comment]
the reason why inside controller instead of directly charts  is because helm requires the folder name to be same as the name mentioned in the chart.yaml. here the ci will just cd to charts, chane the versions and do a `helm package <component-name>` and publish that chart

**Comment by helgi** [comment]
Ok great - that's what my initial question was about :)

Another nit question - Thoughts on dropping `controller-` from the filenames? Is that too excessive / would cause confusion in general when debugging and such?

**Comment by kmala** [comment]
i can remove the prefix but the name in the manifest is what is used for debugging mostly as the k8s objects are with that name and it still has deis prefix which i have plan to remove.

**Comment by helgi** [comment]
Yeah, filename only - I remember the `deis-` removal part, already happened on the files which is nice :) Just got curious if it made sense now that things are even more contained than in the classic version.

Leaving it up to you if you keep the prefix or remove, was just a curiosity of mine.

**Pull request merged**
