### PR TITLE
[WIP] - Feat deployment recreate

### LINKED ISSUE #878: Look at allowing setting the Recreate strategy on Deployment objects
Deployments have RollingUpdate and Recreate. Deis only supports RollingUpdate right now

### PR DESCRIPTION
**Pull request by lachie83**
Implemented initial code and performed basic testing.

Outstanding:
- [ ] Perform more live testing
- [ ] Provide tests
- [ ] Documentation
- [ ] Understand differences between kubctl [replace, apply, patch]

closes #878

### CODE REVIEW

**Comment by helgi** [comment]
@lachie83 Do you want to try to bring this over the line?

**Comment by mboersma** [comment]
@lachie83 is this still in progress, or should we close it?

**Comment by lachie83** [comment]
Hi @mboersma. We had a user at the time that was looking at using this which is why I started work on it. Do you think it's a useful feature to have? If so I can commit to getting the testing done.

**Comment by bacongobbler** [comment]
Yes! I think this would be useful to others for sure. If you have some spare time and want to hack on the rest of the work we'd be happy to get it in.

**Comment by lachie83** [comment]
Fantastic. I'll try and knock it out after the holidays.

**Comment by mboersma** [comment]
I'm going to close this since it's almost a year old, but @lachie83 please re-open if this code gets resurrected.

**Pull request closed without merging**
