### PR TITLE
Get timezone from environment variable

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes https://github.com/deis/deis/issues/5113

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
If you wouldn't mind amending your commit such that it follows the [commit style guide](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#commit-style), that would be awesome! That way it'll get picked up by `deisrel` when we generate the release changelog. Thanks!

**Comment by ChillarAnand** [comment]
Amended commit. Thanks @bacongobbler

**Comment by mboersma** [comment]
Thanks @ChillarAnand! Do we think this change is sufficient, or should we also add this to [the deployment](https://github.com/deis/controller/blob/master/charts/controller/templates/controller-deployment.yaml#L55) and the `values.yaml`:

```yaml
- name: "TZ"
  value: "{{ .Values.time_zone }}"
```

**Comment by bacongobbler** [comment]
Good point @mboersma. @ChillarAnand would you mind making that change so users can modify the timezone from the chart?

the last line probably needs to be

```
value: "{{ default "UTC" .Values.time_zone }}"
```

So that existing charts that don't set the time zone will still work.

**Comment by ChillarAnand** [comment]
Updated. Thanks @mboersma @bacongobbler

**Pull request merged**
