### PR TITLE
fix(scheduler): copy object-storage creds during RC creation instead …

### PR DESCRIPTION
**Pull request by helgi**

### CODE REVIEW

**Comment by smothiki** [comment]
what difference does it make ? creation during RC phase

**Comment by smothiki** [comment]
got it no worries

**Comment by helgi** [comment]
Prior to that I had added a check where we only added the object keys when it was the right build type, however `create` actually gets no information passed to it and actually does not have the build information at the time anyway so it was a dud to begin with

**Comment by mboersma** [comment]
I tested this and it does avoid the `Error syncing pod, skipping: secrets "objectstorage-keyfile" not found` problem.

**Pull request merged**
