### PR TITLE
fix(boot): Don't change group ownership of docker socket

### LINKED ISSUE #1170: Controller changes GID of Docker socket
The startup script for the controller changes the gid of the host's docker.sock to match the gid of the "deis" group inside the controller, which causes members of the "docker" group on the host to loose access to the socket (for example on CoreOS the default "core" user is part of the "docker" group).

It is really bad practice to have a container modify permissions of files it doesn't own inside the host filesystem, so this should be fixed.

This change was made to fix issue #804 where the docker.sock was owned by root on some systems.

I propose a different approach, which would cause the "deis" user to be added to the group with the same gid as the docker socket, if such a group exists inside the container and otherwise add a new group "docker" with the same gid as the docker socket. This could mean that the "deis" user is added to the "root" group (gid 0) on the host on systems affected by #804.

I'll open a PR shortly with the proposed fix (**update:** see #1171).

### PR DESCRIPTION
**Pull request by felixbuenemann**
This is a better fix for issue #804 and fixes #1170:

* The gid of the docker socket is no longer changed to that of the deis group (gid 107).
* If an existing group in the container has the same gid as the socket, we add the deis user to that group (unless of course it is the "deis" group).
* If no such group exists, we create a new "docker" group and add the user to that (like before @bacongobbler's hack in b27c816e9ef21a989c68db23c0c98c02f726cf7b was added, which effectively disabled this code).

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by felixbuenemann** [comment]
As noted in #1170 this could cause the "deis" user to become part of the "root" group, if the socket is own by that group. We could extend the script to echo a warning in that case.

**Comment by felixbuenemann** [comment]
I manually checked that the right thing happens if the socket on the host is currently owner by either "docker", "deis" or "root" by using `kubectl exec -n deis <deis-controller-pod> curl --unix-socket /var/run/docker.sock http:/containers/json` to list the running containers through the mounted socket.

**Comment by kmala** [comment]
Jenkins, Add to whitelist.

**Pull request merged**
