### PR TITLE
fix(registry): User should be able to pull the image from internal registry

### LINKED ISSUE #894: deis pull of image from internal registry should work
You should be able to do a `deis pull <regsitry-ip>:<port>/iamge:tag` basically pull an image already in registry.
we need to remove the striping logic https://github.com/deis/controller/blob/64547741ae6e80f8299992fc57b87d9c10d2c5bd/rootfs/api/models/release.py#L58-L59 as we had removed the registry appending logic in https://github.com/deis/controller/pull/716

### PR DESCRIPTION
**Pull request by kmala**
fixes #894

### CODE REVIEW

**Comment by bacongobbler** [comment]
there's a typo in the commit title: should be "registry". This won't impact us in any way, right?

**Comment by mboersma** [comment]
Could you amend the second commit title? Maybe:
```
tests(build): fix for internal registry access
```

**Comment by kmala** [comment]
all the tests are passing https://ci.deis.io/job/workflow-test-pr/4108/console

**Comment by bacongobbler** [comment]
Doesn't look like Jenkins agrees with that ^ ;)

**Pull request merged**
