### PR TITLE
fix(views): prevent overlapping config:set operations

### PR DESCRIPTION
**Pull request by mboersma**
Uses a file lock to ensure that multiple gunicorn processes can be coordinated in the container. If a `deis config:set` is in progress, another client attempting `config:set` will try to obtain the lock for 5 seconds, then return an error:
```
$ deis config:set POWERED_BY=Second
Creating config... Error: 
409 CONFLICT
error: Config changes already in progress.
[Errno 11] Resource temporarily unavailable
```

See also deis/deis#5008.

### CODE REVIEW

**Comment by helgi** [comment]
Must admit I'm not a big fan of pulling in SimpleLock into more places but I suppose that's hard to prevent without a better operations system going on ;)

My main concern is we are adding logic into the views, logic that should live in the model probably? lock in the model and have the view understand the error so it can throw the 409

**Comment by mboersma** [comment]
>  logic that should live in the model probably

That's a good point. This began as a naive port of deis/deis#4758, but could be improved. I'll take a look at re-homing that code.

**Comment by helgi** [comment]
@mboersma awesome :) just wanted to make use try to use views less for "real" logic because it makes testing easier and reduces the cognitive load when trying to grok the code - We def have places where we kinda ... cheated :P Not that Django is super strict on the separation ;)

**Comment by vdice** [comment]
@mboersma is this PR still intended for the `v2.0-rc1` milestone?

**Comment by bacongobbler** [comment]
LGTM, though we should probably punt this to v2.2 and add docs in the API reference guide, eh?

**Comment by bacongobbler** [comment]
Actually docs shouldn't be necessarily required for this, since it's just a new error code and we don't document the errors returned by the server. Ping @helgi for reviews

**Comment by helgi** [comment]
The deployment pr prevents parallel updates, but only for deployments. Does supersed this PR somewhat

**Comment by bacongobbler** [comment]
Personally I'd still want to merge this even if #854 supercedes this for the unit test alone so we can verify that.

**Comment by helgi** [comment]
Then i would rather see those tests in their own PR. Seems wrong to me to merge flock things we will rip out within days

**Comment by mboersma** [comment]
This isn't relevant now for default deployment-based apps, and we aren't excited about using more `flock` hacks, so I'm closing it.

**Pull request closed without merging**
