### PR TITLE
fix(api): remove command escaping from v1

### LINKED ISSUE #821: cannot run process with multiple arguments
Given the following Procfile for [example-dockerfile-procfile-http](https://github.com/deis/example-dockerfile-procfile-http):

```
web: /bin/boot
worker: while true; do echo hello world; sleep 10; done
sleeper: sleep 900
```

I can scale the web type, but `sleeper` and `worker` both fail after scaling:

```
><> k --namespace=www get po
NAME                   READY     STATUS             RESTARTS   AGE
www-v2-sleeper-a59d2   0/1       CrashLoopBackOff   1          12s
www-v2-web-8ofdm       1/1       Running            0          5m
www-v2-worker-wdok9    0/1       Error              3          45s
><> k --namespace=www logs www-v2-worker-wdok9
true;: -c: line 0: unexpected EOF while looking for matching `''
true;: -c: line 1: syntax error: unexpected end of file
```

And the actual invocation of the command in the k8s manifest looks like this:

```
spec:
  containers:
  - args:
    - bash
    - -c
    - '''while'
    - true;
    - do
    - echo
    - hello
    - world;
    - sleep
    - 10;
    - done'
```

Looks like we need to fix up some of the command parsing logic from v1.

FYI this is on workflow-v2.0.0

### PR DESCRIPTION
**Pull request by bacongobbler**
This code used to be necessary to prevent systemd abuse. Now that kubernetes handles the escaping
for us, there is no need to be super defensive in our own code.

closes #821 
closes https://github.com/deis/deis/issues/5060

### CODE REVIEW

**Comment by bacongobbler** [comment]
pinging @helgi on this one. Whenever I test this PR against https://github.com/deis/example-dockerfile-procfile-http and scale up the worker process, I hit this interesting bug:

```
><> deis scale worker=1
Scaling processes... but first, coffee!
Error: 
503 Service Unavailable
detail: Single '}' encountered in format string
```

The controller logs aren't very helpful either...

```
INFO scale www-v2-worker, img 10.247.225.28:80/www:git-0c483886, cmd "while true; do echo hello world; sleep 10; done"
ERROR [www]: www-v2-worker (scale): Single '}' encountered in format string
10.246.64.14 "POST /v2/apps/www/scale/ HTTP/1.1" 503 52 "Deis Client v2.0.0"
```

**Comment by bacongobbler** [comment]
back up for review again. Now whenever I run `deis run echo hi` I hit #862 which is solved by running `deis config:set PORT=5000` before running that command.

Manual testing:

1. deploy a deis cluster with this PR
2. deploy [example-dockerfile-procfile-http](https://github.com/deis/example-dockerfile-procfile-http)
3. `deis scale worker=1` should work and the process should be responsive
4. `deis run echo hi` should also work

**Comment by bacongobbler** [comment]
Hold up; still seeing the same error when scaling the worker process...

```
detail: Single '}' encountered in format string
```

**Comment by bacongobbler** [comment]
Aha, now I'm actually getting logs this time!

```
ERROR:root:Single '}' encountered in format string
Traceback (most recent call last):
  File "/app/scheduler/__init__.py", line 255, in scale
    self.create_rc(namespace, name, image, entrypoint, command, **kwargs)
  File "/app/scheduler/__init__.py", line 907, in create_rc
    manifest['spec']['template'] = self._build_pod_manifest(namespace, name, image, **kwargs)
  File "/app/scheduler/__init__.py", line 357, in _build_pod_manifest
    self._set_container(namespace, container_name, container, **kwargs)
  File "/app/scheduler/__init__.py", line 470, in _set_container
    self.update_secret(namespace, secret_name, secrets_env)
  File "/app/scheduler/__init__.py", line 1107, in update_secret
    name, namespace
scheduler.KubeHTTPException: ('failed to failed to update Secret "www-v2-env" in Namespace "www": 400 Bad Request\n{\'metadata\': {}, \'message\': \'Secret in version "v1" cannot be handled as a Secret: [pos 398]: json: error decoding base64 binary \\\'80\\\': illegal base64 data at input byte 0\', \'apiVersion\': \'v1\', \'status\': \'Failure\', \'kind\': \'Status\', \'code\': 400, \'reason\': \'BadRequest\'}', 'www-v2-env', 'www')
```

**Comment by bacongobbler** [comment]
K, I have gone through the manual steps and all looks good now. Manual steps have been updated and I have fixed and/or otherwise filed issues for problems I have encountered. Ready for review!

**Comment by bacongobbler** [comment]
aha, good thing we have e2e tests. e2e found an issue with `deis pull` apps with this change. Fixing

**Comment by bacongobbler** [comment]
fixed. c'mon jenkins!

**Comment by bacongobbler** [comment]
Hmm, now this is an interesting error:

> 13:57:57 Error: Unknown Error (503): {"detail":"(list pods): Release matching query does not exist."}

Don't think that's related so I'll re-run CI but I'll take a look.

**Comment by bacongobbler** [comment]
@smothiki mentioned to me in slack that this is unrelated

**Comment by helgi** [comment]
Manually tested. LGTM

**Pull request merged**
