### PR TITLE
feat(label-cmd): support new label cmd

### PR DESCRIPTION
**Pull request by zinuzoid**
Support new label command. https://github.com/deis/workflow-cli/pull/273
Labels are general key value string to each app just for administration purpose.
e2e https://github.com/deis/workflow-e2e/pull/337
See https://github.com/deis/workflow/issues/597

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by kmala** [comment]
Jenkins, Add to whitelist.

**Comment by zinuzoid** [comment]
hmm, seems like failed case isn't related to this PR. [https://travis-ci.org/deis/controller/builds/178680541#L383](https://travis-ci.org/deis/controller/builds/178680541#L383)
`AssertionError: Regex didn't match: 'klutzy-yodeling-web-[0-9]{8,10}-[a-z0-9]{5}' not found in 'klutzy-yodeling-web-9283091-v4u9j'`

possible fixes.
- re-run test it should pass eventually.
- proper fix would be update regex to `klutzy-yodeling-web-[0-9]{7,10}-[a-z0-9]{5}`

**Comment by kmala** [comment]
Tested manually:
```
ENG001599:example-go keerthanmala$ deis labels
=== karmic-mackinaw Label
No labels found.
ENG001599:example-go keerthanmala$ deis labels:set TEST=test1
Applying labels on karmic-mackinaw... done
ENG001599:example-go keerthanmala$ deis labels
=== karmic-mackinaw Label
TEST:            test1
ENG001599:example-go keerthanmala$ deis labels:unset TEST
Removing labels on karmic-mackinaw... done
ENG001599:example-go keerthanmala$ deis labels
=== karmic-mackinaw Label
No labels found.
```

**Pull request merged**
