### PR TITLE
feat(registry): add initial support to auth to an external Registry on per app basis

### PR DESCRIPTION
**Pull request by helgi**
## Summary of Changes

This will allow for setting username and password for an external registry to pull images from

`IMAGE_AUTH_USER` and `IMAGE_AUTH_PASSWORD` are support via `config:set` and this is per application.

Currently Docker Hub and Quay are supported and a basic support for long lived tokens under gcr.io - ECR is not supported at this time.

For GCR see https://cloud.google.com/container-registry/docs/auth#using_a_json_key_file
The JSON blob needs to be compacted using `jq -c .` or similar before being set

The UX for this will change, very soon. Doing a separate PR for that

## Issue(s) that this PR Closes

Please list the issue(s) that this PR closes, similar to the below:
ref #639
ref #253 

## Associated [End To End Test](https://github.com/deis/workflow-e2e) PR(s)

Will come when UX has been sorted out

## Associated [Documentation](https://github.com/deis/workflow) PR(s)

Will come when UX has been sorted out

# Associated [Design Document](http://docs.deis.io/en/latest/contributing/design-documents)(s)

https://github.com/deis/workflow/issues/163
https://github.com/deis/controller/issues/639

## Testing Instructions

Please provide a detailed list for how to test the changes in this PR.

1. Create a Deis Cluster
2. Register an app
3. Create a Private Repo on Quay.io
4. Set user / pw via `IMAGE_AUTH_USER` and `IMAGE_AUTH_PASSWORD` using `config:set` for the app
5. Do `deis pull` referencing an image in a private repo

Also, please provide a description of the desired result after the tester completes the above steps.

1. The app called "abcd" should be deployed using the private image

## Pull Request Hygiene TODOs

Please make sure the below checklist is complete.

- [x] Your pull request is concise and to the point (make another PR for refactoring nearby code)
- [x] Your commits are squashed into logical units of work
- [x] Your commits follow the [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)

:cherry_blossom: Thank you! :cherry_blossom:

### CODE REVIEW

**Comment by bacongobbler** [comment]
This might be a clean way to attach credentials to a `git push deis master` as well. :+1: 

Could you also please write out some junk e2e tests and some documentation in deis/workflow?

**Comment by helgi** [comment]
@bacongobbler Not going to write e2e or documentation for this PR, going to do it when I finish the UX, which will be tomorrow most likely. I wanted to keep separation of concerns, as to not overload a single PR

**Comment by bacongobbler** [comment]
Isn't the UX just `deis config:set IMAGE_AUTH_USER=bacongobbler IMAGE_AUTH_PASSWORD=secret` as per https://github.com/deis/workflow/issues/163, or is there another proposal on the way?

**Comment by helgi** [comment]
There is a different UX being talked about, it's basically making registry a top level object like tags, thay way credentials don't make their way into env vars

**Comment by aledbf** [comment]
@helgi why not `imagePullSecrets` in the spec?

**Comment by helgi** [comment]
@alefsbf Next iteration (happening soon) will include that option - this time around I am pulling into local registry

**Pull request merged**
