### PR TITLE
fix(boot): change group ownership of docker socket

### LINKED ISSUE #801: permission denied connecting to docker.sock
workflow-v2.0.0 on vagrant.

while attempting a `deis pull`, I could not pull the image because the controller cannot establish a connection with the docker socket:

```
INFO [go]: bacongobbler deployed deis/example-go
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/docker/unixconn/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/docker/unixconn/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 97, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.5/dist-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 120, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 171, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 246, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 60, in create
    source_version=self.version
  File "/app/api/models/release.py", line 87, in new
    release.publish()
  File "/app/api/models/release.py", line 134, in publish
    publish_release(source_image, self.image, deis_registry, self.get_registry_auth())
  File "/app/registry/dockerclient.py", line 197, in publish_release
    return DockerClient().publish_release(source, target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 31, in __init__
    self.client = docker.Client(version='auto', timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 81, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 105, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
10.246.71.12 "POST /v2/apps/go/builds/ HTTP/1.1" 500 25 "Deis Client v2.0.0-dev"
```

From inside the container I notice that the docker socket is owned by root:

```
root@deis-controller-z0rnr:/var/run# ls -al
total 24
drwxr-xr-x.  1 root root 4096 Jun  8 19:21 .
drwxr-xr-x.  1 root root 4096 Jun  8 19:21 ..
srw-rw----.  1 root root    0 Jun  8 17:59 docker.sock
-rw-r--r--. 64 root root    0 Apr 21 18:33 init.upgraded
drwxrwxrwt.  2 root root 4096 Mar 31 08:21 lock
drwxr-xr-x.  2 root root 4096 Jun  8 18:57 mount
drwxr-xr-x.  5 root root 4096 Jun  8 19:21 secrets
drwxr-xr-x.  2 root root 4096 Jun  8 18:57 systemd
-rw-rw-r--. 64 root utmp    0 Mar 31 08:21 utmp
```

changing the socket owner to `deis:deis` seemed to do the trick:

```
root@deis-controller-z0rnr:/var/run# chown deis:deis docker.sock
root@deis-controller-z0rnr:/var/run# exit
$ deis pull deis/example-go
Creating build... ..o
```

### PR DESCRIPTION
**Pull request by bacongobbler**
# Summary of Changes

on some providers, the docker socket is owned by the root group. We want it to be owned by docker
so the controller can connect to the socket.

# Issue(s) that this PR Closes

closes #801 

# Associated [End To End Test](https://github.com/deis/workflow-e2e) PR(s)

N/A since this occurs only on vagrant

# Associated [Documentation](https://github.com/deis/workflow) PR(s)

N/A

# Associated [Design Document](http://docs.deis.io/en/latest/contributing/design-documents)(s)

N/A

# Testing Instructions

1. Create a Deis Cluster on Vagrant using kube-up.sh
2. Register an app
3. Deploy an app using `deis pull`

Results:

1. The app called "abcd" should be deployed.

# Pull Request Hygiene TODOs

Please make sure the below checklist is complete.

- [x] Your pull request is concise and to the point (make another PR for refactoring nearby code)
- [x] Your commits are squashed into logical units of work
- [x] Your commits follow the [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)

:cherry_blossom: Thank you! :cherry_blossom:

### CODE REVIEW

**Comment by bacongobbler** [comment]
removing from v2 milestone as there is a workaround for this, and this only affects one provider (vagrant).

**Comment by bacongobbler** [comment]
also error logs from the controller on the last run:

```
system information:
Django Version: 1.9.7
Python 3.5.1+
chgrp: invalid group: 'docker'
```

**Comment by jwalters-gpsw** [comment]
If I wanted to apply this fix to the current release for a deployed system, what do I need to do? (Getting the 500 internal error on vagrant based system)

**Comment by bacongobbler** [comment]
You can follow the guide on [setting up your development environment](https://deis.com/docs/workflow/contributing/development-environment/) and apply the change from there.

For controller specifically, the command invocation is `make deploy` after this is all set up.

**Comment by mboersma** [comment]
@bacongobbler if you rebase this against master, do the two housekeeping commits (`Merge branch 'master' into 801-chgrp-docker`) go away? Otherwise LGTM.

**Comment by bacongobbler** [comment]
Yes, I will use the ["squash and merge approach"](https://github.com/blog/2141-squash-your-commits) from the github API, which will squash these commits into a single commit. :)

**Pull request merged**
