### PR TITLE
feat(api): allow app names up to 63 characters in length

### PR DESCRIPTION
**Pull request by bacongobbler**
closes deis/workflow#212.

### CODE REVIEW

**Comment by tmc** [comment]
@bacongobbler ci failure is from `         #logging.disable(logging.ERROR)` line

**Comment by bacongobbler** [comment]
@tmc that line is to enable debug logging to see what's going on in CI. I'm focused on their work right now but please feel free to take this up if you have cycles. I'll get back to this eventually.

**Comment by bacongobbler** [comment]
personal note: needs a rebase on top of #1199 as well

**Comment by bacongobbler** [comment]
I vastly simplified this PR to just bump the maximum app name length to 63 characters. I don't imagine we have anyone running Workflow v2.13 on a k8s 1.3 cluster any more... Everyone is running at least 1.4.

**Comment by bacongobbler** [comment]
Jenkins, test this please.

**Pull request merged**
