### PR TITLE
Improve development workflow

### PR DESCRIPTION
**Pull request by dhoeric**
# Summary of Changes

- Make use of docker image cache for building controller image
- Always pull the image from image repository on `make deploy`

# Testing Instructions

Run `make build deploy`

# Pull Request Hygiene TODOs

Please make sure the below checklist is complete.

- [x] Your pull request is concise and to the point (make another PR for refactoring nearby code)
- [x] Your commits are squashed into logical units of work
- [x] Your commits follow the [commit style guidelines](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide)

:cherry_blossom: Thank you! :cherry_blossom:

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by bacongobbler** [comment]
this was done recently in https://github.com/deis/controller/commit/eba900ff35ecf5b3a51429ce86874b93db65b2e4, but thank you for the PR!

**Comment by dhoeric** [comment]
@bacongobbler How about the commit of `Always` pull docker image when `make deploy`?

**Comment by bacongobbler** [comment]
when testing changes you should be using `workflow-dev` which already has an image pull policy of "always". It's just the official releases that do not. :)

**Pull request closed without merging**
