### PR TITLE
docs(README): Fix typo in pyenv instructions.

### PR DESCRIPTION
**Pull request by robholland**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by vdice** [comment]
Jenkins, add to whitelist.

**Comment by bacongobbler** [comment]
@robholland can you rebase this PR? Once that's done we can merge this.

**Comment by bacongobbler** [comment]
Never mind. Master [has this change](https://github.com/deis/controller#python). Thanks!

**Pull request closed without merging**
